### ISSUE TITLE
Come up with ideas for game jam

### ISSUE THREAD

**Issue by D4ngerKitty** [D4ngerKitty/Gameideas#2]
Game Jam link https://arcade.makecode.com/gamejam/global-2021
@UnsignedArduino do you have time to come up with ideas and build a game with me?
Game jam starts in nine days

**Comment by D4ngerKitty** [comment]
idea farming game if the jam is wildlife jam.

**Comment by UnsignedArduino** [comment]
@LucasMayhew what style? like we have an inventory and we do farming and we get stuff in inventory?

**Comment by UnsignedArduino** [comment]
hopefully school doesn't decide against this

**Comment by D4ngerKitty** [comment]
Inventory using your inventory extension. You can sell the stuff you grow and buy upgrades then there is seasons that have different plants.

**Comment by D4ngerKitty** [comment]
Made a small farm game demo
https://makecode.com/_5g427HEEtWpe
I think that it looks good. I would like to do a game like this for the game jam

**Comment by UnsignedArduino** [comment]
nice!

**Comment by D4ngerKitty** [comment]
another idea Rain forest RPG platformer that has lots of shades of green

**Comment by UnsignedArduino** [comment]
i think a platformer would be nice! i could make the mechanics and then you make the amps? or the other way around? idrc but I'm not good at art like you :)

**Comment by UnsignedArduino** [comment]
maps*

**Comment by D4ngerKitty** [comment]
There also could be a story like a boy and his dog are in the jungle but then the boy find a evil magician who stills his dogs life and the dog is week and the boy has to face off the magician to save his dog

**Comment by UnsignedArduino** [comment]
that's sad T.T

**Comment by D4ngerKitty** [comment]
I know but that story makes you want to save the dog and face the magician

**Comment by D4ngerKitty** [comment]
Made a small Demo for the tiles for the jungle RPG idea
https://makecode.com/_hdhbkY3zUTJ1

**Comment by D4ngerKitty** [comment]
Do you have any ideas

**Comment by UnsignedArduino** [comment]
i think the jungle rpg is good

**Comment by UnsignedArduino** [comment]
i'll see if i can add more stuff to tilemap and make it a working platformer

**Comment by UnsignedArduino** [comment]
i fixed it up a bit: https://makecode.com/_7v63CX56YCzj
(love the art so much)
and made it more modular and stuff
also we need a main character, doggo, evil magician, and title

**Comment by UnsignedArduino** [comment]
has player: (used default for now, you can change it if you wish too) https://makecode.com/_iey83P7d4TDA

**Comment by UnsignedArduino** [comment]
version with transitions: https://makecode.com/_d3Wcu1ci1PtR

**Comment by D4ngerKitty** [comment]
Note that this is not the game we are making for the game jam it was just a demo so you can get the idea I had

**Comment by UnsignedArduino** [comment]
oh ok

**Comment by UnsignedArduino** [comment]
so what did you wanted to do? use that? or make a "better" one if we commit to that

**Comment by D4ngerKitty** [comment]
We could use some of the code though I like the transitions and I also came up with an idea for having a phoenix make the hero have fire power.

**Comment by UnsignedArduino** [comment]
maybe the player stumbles upon a temple for the phoenix and "accidentally" wakes it up

**Comment by D4ngerKitty** [comment]
We don't know the theme yet so there is a chance we can't make this game

**Comment by UnsignedArduino** [comment]
that's true

**Comment by UnsignedArduino** [comment]
if it is, then we can continue with this idea

**Comment by UnsignedArduino** [comment]
but i think there is a pretty high chance that the theme is "save the trees" and something along those lines

**Comment by D4ngerKitty** [comment]
Yes

**Comment by D4ngerKitty** [comment]
https://makecode.com/_ADVRAy6EpP0  phoenix temple  idea

**Comment by D4ngerKitty** [comment]
Link not working
https://makecode.com/_ADVRAy6EpP0o

**Comment by D4ngerKitty** [comment]
Made better lighting
https://makecode.com/_U25VAaekg6p7

**Comment by D4ngerKitty** [comment]
Added particles https://makecode.com/_UkXDF4bRTHWv

**Comment by D4ngerKitty** [comment]
I wonder when Makecode will post a hint like last time

**Comment by UnsignedArduino** [comment]
idk if they are going to, maybe ask during stream?
if not, you could ask for one :p

**Comment by D4ngerKitty** [comment]
https://makecode.com/_UpjF9tAAwgaH
Made some animations we can use latter

**Comment by UnsignedArduino** [comment]
omg that looks amazing wow 😍
imagine being able to do pixel art T.T

**Comment by D4ngerKitty** [comment]
@UnsignedArduino can you work on a sound track for are game make shore the songs aren't copyrighted. So what I am asking is can you make some songs for our game.

**Comment by UnsignedArduino** [comment]
i can _try_ to compose something original but I can make no guarantees

is this enough: (and it's jungle theme right?)

- [ ] battle music
- [ ] ambient music

**Comment by UnsignedArduino** [comment]
:/ it's ok (ambient music test)
https://makecode.com/_UT3R84gTYVsA

**Comment by D4ngerKitty** [comment]
I would like both ambient music for the phoenix temple and battle for the boss fight and lively for the title.

**Comment by D4ngerKitty** [comment]
Made some music 
https://makecode.com/_Ro8Rp3dAsCYz

**Comment by D4ngerKitty** [comment]
game jam starts in 3 days

**Comment by D4ngerKitty** [comment]
I will let you do the rest of the music
but I made some more animations
https://makecode.com/_4fzTdVRH2Lie
Made wizard
Improved the sword attack

**Comment by D4ngerKitty** [comment]
I am guessing you have been busy with school

**Comment by D4ngerKitty** [comment]
@UnsignedArduino I would like it if you did the music because I don't really like doing music I would rather make pixel art.

**Comment by UnsignedArduino** [comment]
yes i'll do music u do art :)

**Comment by UnsignedArduino** [comment]
yes i can make music

**Comment by D4ngerKitty** [comment]
So I what if we have this dragon boss and if you beet him you get a sword that is like the master sword in Zelda.

**Comment by UnsignedArduino** [comment]
will that be the end of the game? cause if not then we get to make an inventory system, or just default to using the most recent weapon obtained

**Comment by D4ngerKitty** [comment]
No inventory unless you what to code that. I was thinking that the sword just does more damage.

**Comment by UnsignedArduino** [comment]
i def don't want to write an inventory lol
yea more dmg sword is better and simpler

**Comment by UnsignedArduino** [comment]
Ambient music again: https://makecode.com/_AUPHzMY9ccUA

**Comment by UnsignedArduino** [comment]
Battle music: https://makecode.com/_XigJccEj9bwK

**Comment by UnsignedArduino** [comment]
https://makecode.com/_hhfCF01RcLPr

Press A to cycle through both of them in the demo
I think the fading volume effect works well here

**Comment by D4ngerKitty** [comment]
This is great love the music!

**Comment by D4ngerKitty** [comment]
We might have to do the farming game or have the villain damage the CLIMATE and you have to fix it  by planting trees and the phoenix give you the power to plant flowers and trees.

**Comment by D4ngerKitty** [comment]
idea the people who live in a magical forest fill the clement change and go to the cites to stop it.

**Comment by UnsignedArduino** [comment]
> have the villain damage the CLIMATE and you have to fix it by planting trees and the phoenix give you the power to plant flowers and trees.
i think something like this:
- you are minding your own business in the forest
- you see smoke in the distance
- you go over to check it out
- you see a villain burning everything to the ground for farming space
- then you go to tell him to stop but then he runs away, so you have to chase after him
- then you will keep going on farther into a jungle instead of just forest
- there will be phoenix temple you stumble into
- "accidentally" wake the phoenix up
- appease the phoenix like complete a level
- then the phoenix gives you seeds that when they hit the ground they grow almost instantly
- so you have to restore the jungle before the villain can burn everything down
- then idk from here

**Comment by D4ngerKitty** [comment]
Well I think the theme is more of how can we change the enrolment
So am idea is that the Phoenix guardian sends a hero to save CLIMATE form changing more and to change the way energy works 
but to change stuff the hero has to play mini games like mining and building.

**Comment by D4ngerKitty** [comment]
Okay I am going to start making the game with a start screen the Phoenix and save files
you can work on the mini games I would like it if the play had to play the mini games with his sword but first 
We have to make the hero can you code him you the animations I made

**Comment by UnsignedArduino** [comment]
ok so actually first should i start
I'll take the animations and put it into a sprite
which will activate different animations neccessary

**Comment by UnsignedArduino** [comment]
what are we gonna call the game

**Comment by D4ngerKitty** [comment]
The Phoenix's Quest

**Comment by UnsignedArduino** [comment]
is this gonna be platformer like we have to press up to jump or like "top-down-side" view where we can move in all directions like my attack of the serpents

**Comment by D4ngerKitty** [comment]
Platformer

**Comment by UnsignedArduino** [comment]
ok working on it rn

**Comment by UnsignedArduino** [comment]
here add tilemap and stuff
https://makecode.com/_UMVEaEVvgbKz

**Comment by D4ngerKitty** [comment]
Next we need the player to be able to hit stuff with his sword

**Comment by UnsignedArduino** [comment]
ok pls send link when you add tilemap even just for testing

**Comment by D4ngerKitty** [comment]
Okay

**Comment by D4ngerKitty** [comment]
Added Tile map 
https://makecode.com/_6AFA0adgD3oJ

**Comment by UnsignedArduino** [comment]
ty doing more stuff rn

**Comment by D4ngerKitty** [comment]
I am working on more stuff

**Comment by UnsignedArduino** [comment]
should a key be attack and b be for something else?

**Comment by D4ngerKitty** [comment]
Maybe  it is up to you

**Comment by UnsignedArduino** [comment]
ok

**Comment by UnsignedArduino** [comment]
sorry for taking so long

**Comment by D4ngerKitty** [comment]
Added start screen
https://makecode.com/_1i3WRhVECWr2

**Comment by D4ngerKitty** [comment]
It is okay

**Comment by UnsignedArduino** [comment]
here with attacking animations and variable will indicate is attacking so we can use it for overlap events
https://makecode.com/_8sbUwATqq7Xd

**Comment by UnsignedArduino** [comment]
we should add in start screen last prob but I love it ✨✨✨♥♥♥

**Comment by UnsignedArduino** [comment]
i gtg for today

**Comment by D4ngerKitty** [comment]
Okay I am going to do one more update then I will go to

**Comment by D4ngerKitty** [comment]
I am done 
https://makecode.com/_P2D1CX1s8d74
Save done Start screen done
Story??????

**Comment by UnsignedArduino** [comment]
no idea
maybe you are an adventurer and you stumble upon the phoenix temple
then bunch of dialog of phoenix eplaingin the climate change
then the mission
then you go off and do the mission

**Comment by D4ngerKitty** [comment]
Have you worked on the game lately

**Comment by D4ngerKitty** [comment]
I am going to start working on the story

**Comment by UnsignedArduino** [comment]
no you have the latest version

**Comment by D4ngerKitty** [comment]
Do you think that the player should have a name

**Comment by UnsignedArduino** [comment]
I think you can just ask the player for name (with ask string) then use that

**Comment by D4ngerKitty** [comment]
Latest version https://makecode.com/_fYcbKECzU750
We can have it were there is mutable levels and each one has its own theme.

**Comment by UnsignedArduino** [comment]
i'll try to add this code in the other version later (with the actual platformer)

**Comment by D4ngerKitty** [comment]
Okay

**Comment by D4ngerKitty** [comment]
Big update the trash in the first level will be a trash monster that you have to take out 
https://makecode.com/_f46Jszh42Awj

**Comment by UnsignedArduino** [comment]
so almost like your three brave cats lol but nice

**Comment by UnsignedArduino** [comment]
starting in the seas heehe

**Comment by D4ngerKitty** [comment]
Like making games in the ocean there will be other places

**Comment by UnsignedArduino** [comment]
Added start screen: https://makecode.com/_FLiV7PL4ogJy

**Comment by UnsignedArduino** [comment]
i will prob add a couple levels which are platformers so you "explore" and "accidentally" stumble upon the phoenix temple

**Comment by UnsignedArduino** [comment]
extended the first level: https://makecode.com/_URFeyoXtcXgz

**Comment by UnsignedArduino** [comment]
made second level tilemap: https://makecode.com/_X6jeYvbz5Lpe

**Comment by D4ngerKitty** [comment]
I am going to try and merge the two defiant versions together

**Comment by UnsignedArduino** [comment]
i am in the middle of making my version transition between levels automatically

**Comment by UnsignedArduino** [comment]
but if you want to do it your level selector style with the big map

**Comment by UnsignedArduino** [comment]
that would be nicer

**Comment by D4ngerKitty** [comment]
Okay

**Comment by UnsignedArduino** [comment]
transitions between levels
https://makecode.com/_ddkVvqL0Y2EF

**Comment by UnsignedArduino** [comment]
if you want the nice map it shouldn't be that hard - it just needs to call the level functions when appropriate

**Comment by D4ngerKitty** [comment]
Okay

**Comment by UnsignedArduino** [comment]
done "some" dialog and will now ask the player for name: https://makecode.com/_Lbp3EuXMhAfV
if you want to clear all settings hold b and reset the game (checks if b key is pressed on start up)

**Comment by D4ngerKitty** [comment]
I got every thing meagered can you work off of this because This took almost an hour 
https://makecode.com/_V058RPAu30Lm

**Comment by UnsignedArduino** [comment]
ok i'll see

**Comment by UnsignedArduino** [comment]
i'll put my changes into yours

**Comment by D4ngerKitty** [comment]
The dragon will be the finale boss and will be called Wildfire

**Comment by UnsignedArduino** [comment]
ok rn i'm adding my features into yours

**Comment by UnsignedArduino** [comment]
so it might be easier if only one person works on it at a time

**Comment by D4ngerKitty** [comment]
Okay

**Comment by UnsignedArduino** [comment]
I've refactored literally everything so it's more like each function has to handle everything in a while loop so it's more maintainable without having to add too much onto the button handlers.
I have everything except the phoenix giving you the mission and the team seas level in: https://makecode.com/_E30d1bXLVVcy
(don't work on this yet - but I wanted you to see so far)
TODO: Be able to show what level the save is on and clean the specific save in the save select menu

**Comment by D4ngerKitty** [comment]
Yes I looks awesome

**Comment by D4ngerKitty** [comment]
Amazing Work @UnsignedArduino

**Comment by D4ngerKitty** [comment]
the first cupule of levels should can teach you how to play the game.

**Comment by UnsignedArduino** [comment]
thanks :D  - hopefully i can continue more tonight otherwise I'll continue tomorrow - but either way we should brainstorm more levels

**Comment by UnsignedArduino** [comment]
like for the trash collecting game (level 4) should we just have to go near it to pick it up and you have to collect all the trash within like 30 secs

**Comment by UnsignedArduino** [comment]
sorry i'm really busy today i won't be able to add anything today but I did improve the title screen, save, and level selector: https://makecode.com/_CPzX5PK8oEpj
pls work off of this

**Comment by D4ngerKitty** [comment]
I know it isn't much because I was busy too but I added the Phoenix 
https://makecode.com/_b3TeKiiui1Wf

**Comment by D4ngerKitty** [comment]
I was thinking for teem seas level we split it in two the first level you defeat trash that has magically come to life and clean up all 20 pieces  of trash that the trash enemies drop. then for the next level you have to beat a  trash mini boss

**Comment by UnsignedArduino** [comment]
i think the first level should be clean up all the trash, the second beach level defeat the magical trash, then the third level a trash mini boss but yes I like that

**Comment by UnsignedArduino** [comment]
cleaned up level 3: https://makecode.com/_WLkTPWfFMLhL

**Comment by UnsignedArduino** [comment]
fixed dialog for level 3: https://makecode.com/_UTWRhH3vCfex

**Comment by UnsignedArduino** [comment]
Added level 5 and 6 tiles in level selector: https://makecode.com/_M7cLAdM4wayw

**Comment by UnsignedArduino** [comment]
level 4 template: https://makecode.com/_JRUhLhiTbJJP

**Comment by D4ngerKitty** [comment]
Can I work off of this?

**Comment by UnsignedArduino** [comment]
yes

**Comment by UnsignedArduino** [comment]
pls tell me if you want to work on the last link you sent cause I don't want to cause another conflict 👍

**Comment by D4ngerKitty** [comment]
Okay I am working on the link you sent

**Comment by D4ngerKitty** [comment]
Made One of the trash levels 
https://makecode.com/_W3zVYJ1Rs7JX

**Comment by D4ngerKitty** [comment]
I am going to be done today

**Comment by UnsignedArduino** [comment]
no rush!

**Comment by UnsignedArduino** [comment]
love the trash collecting level though!!!

**Comment by UnsignedArduino** [comment]
@LucasMayhew are you working on a level rn

**Comment by UnsignedArduino** [comment]
cause if not then i'll continue

**Comment by D4ngerKitty** [comment]
No work off of this 
https://makecode.com/_9h2WiP5DrCrP
Can you make the next level I am going to draw the trash moister  today but you can start coding hem

**Comment by UnsignedArduino** [comment]
okokok

**Comment by UnsignedArduino** [comment]
hopefully after homework i can but i just wanted to know

**Comment by D4ngerKitty** [comment]
Made trash https://makecode.com/_fKUM0T8uE2yq

**Comment by UnsignedArduino** [comment]
Polished level 4: https://makecode.com/_h3JbdMCs4aUq

**Comment by UnsignedArduino** [comment]
Level 4 now has 45 second timer (plus 2 seconds for fade in time so it's synced well) https://makecode.com/_64k7zP5brP7H

**Comment by UnsignedArduino** [comment]
Made the title screen and save selector show particles from the beginning so it looks better: https://makecode.com/_UHeJTJadAJsK

**Comment by UnsignedArduino** [comment]
This version will default to save 1 so you don't have to wait forever to get to the level selector: https://makecode.com/_3Lkbk7a9WE3i

**Comment by UnsignedArduino** [comment]
Started work on level 5 but not done yet: https://makecode.com/_FfU3qz989JeD

**Comment by D4ngerKitty** [comment]
Wow You have been busy.

**Comment by UnsignedArduino** [comment]
Level 5 done: https://makecode.com/_HJL82P3Vu02X

**Comment by UnsignedArduino** [comment]
Started level 6: https://makecode.com/_hRWEzx0fYEi5 (no monster yet)

**Comment by UnsignedArduino** [comment]
What are we going to do for the next levels? Should there be a burned out area and you have to plant trees maybe?

**Comment by UnsignedArduino** [comment]
Added your boss that just sits there: https://makecode.com/_Ph66KJf6AewE

**Comment by UnsignedArduino** [comment]
You can now kill the boss that is just a sitting duck: https://makecode.com/_ErcgjiTX8fJU

**Comment by UnsignedArduino** [comment]
Switched the hardcoded skip into a conditional so there is now a variable called "dev mode" which skips the title screen, save screen, (still defaults to save 1) and unlocks all levels automatically: https://makecode.com/_cUga7c36JTym

**Comment by UnsignedArduino** [comment]
Finished level 6: https://makecode.com/_MXLMjJdKkCLw

**Comment by D4ngerKitty** [comment]
Can I code off of this

**Comment by D4ngerKitty** [comment]
I am going to make Butten B make the player run

**Comment by UnsignedArduino** [comment]
ok

**Comment by D4ngerKitty** [comment]
Made level  7
https://makecode.com/_E1Rb8rTkrHmU

**Comment by D4ngerKitty** [comment]
I think I made level 7 a bit to hard

**Comment by D4ngerKitty** [comment]
I am working on a big update

**Comment by D4ngerKitty** [comment]
Added level 8
https://makecode.com/_7kETWaUE7iwe

**Comment by D4ngerKitty** [comment]
For one of the level I want their to be a huge ice Gollum and you have to stop it form melting

**Comment by D4ngerKitty** [comment]
https://makecode.com/_EerD57aA6UU2 
Made another boss

**Comment by UnsignedArduino** [comment]
Polished level 7: https://makecode.com/_brc0s1iYta5i

**Comment by UnsignedArduino** [comment]
Polished level 8: https://makecode.com/_D9qiDxHTL4it

**Comment by UnsignedArduino** [comment]
Polished level 9: https://makecode.com/_Td0g1W8HVJ5s

So what should we do for the next levels? And maybe after the next icy levels, we can go back to the phoenix and he'll tell us we have done well for now. And then end scene?

**Comment by D4ngerKitty** [comment]
I was thinking for the last ice level we make a ice Gollum fight a gait dragon named wildfire and have the last level you rematch the dragon and after you bet him you talk to the phoenix and then Credits

**Comment by UnsignedArduino** [comment]
ice golem vs. wildfire as a cutscene? and then you have to beat wildfire?

**Comment by D4ngerKitty** [comment]
Well you help the ice golem beat wildfire but if  ice golem dies you loess

**Comment by UnsignedArduino** [comment]
oh ok so the ice golem is just a "CPU" that "helps" us against wildfire
I was thinking we _could_ also do something with wildfires maybe in the forest after the ice part so wildfire actually came from somewhere idk we might not have time for that

**Comment by D4ngerKitty** [comment]
Made some art 
https://makecode.com/_b5jc9oK9jEjL

**Comment by UnsignedArduino** [comment]
I've made the end tile now i'm making the end credits because I want to get that in so we can say like "thanks for playing" https://makecode.com/_ipmEYd9TfE3x

**Comment by UnsignedArduino** [comment]
because we might not be able to finish :(

**Comment by UnsignedArduino** [comment]
Finished end level: https://makecode.com/_Vyrcam29A4Yy

**Comment by UnsignedArduino** [comment]
Hopefully we will be able to add ice levels

**Comment by D4ngerKitty** [comment]
Okay

**Comment by D4ngerKitty** [comment]
I am going to work on the ice levels

**Comment by D4ngerKitty** [comment]
Really focused on  art and tiles so I started level 10
https://makecode.com/_Eqv8MJgM9f6T
Todo 
Make water kill you in this level because its cold
Make heart heal you like in three brave cats

**Comment by UnsignedArduino** [comment]
this level is **nice** :p

**Comment by UnsignedArduino** [comment]
@LucasMayhew you still working on levels?

**Comment by D4ngerKitty** [comment]
Yes

**Comment by D4ngerKitty** [comment]
Hi Finished level 10 
https://makecode.com/_Dh8UbsbE71wM

**Comment by UnsignedArduino** [comment]
Polished level 10: https://makecode.com/_igJc3bgb2RU5

**Comment by D4ngerKitty** [comment]
Yes I am going to start the last level

**Comment by UnsignedArduino** [comment]
ok

**Comment by UnsignedArduino** [comment]
like final boss fight

**Comment by UnsignedArduino** [comment]
then we are done!

**Comment by D4ngerKitty** [comment]
Yes
the boss fight

**Comment by D4ngerKitty** [comment]
It is done
https://makecode.com/_gte58cXuEdi5

**Comment by D4ngerKitty** [comment]
You can make the boss fight easier if you want

**Comment by D4ngerKitty** [comment]
Added some more stuff 
https://makecode.com/_8AAEyU0jkEVK

**Comment by D4ngerKitty** [comment]
Today is the last day

**Comment by D4ngerKitty** [comment]
https://makecode.com/_bbM3W4iR2XLt
added hiden dev mode if your name is devcat you go into dev mode

**Comment by D4ngerKitty** [comment]
https://makecode.com/_YmRKmwh2qdsR
fixed hiden dev mode

**Comment by D4ngerKitty** [comment]
Are you still here?

**Comment by UnsignedArduino** [comment]
yes lol

**Comment by UnsignedArduino** [comment]
i was trying to finish the last level

**Comment by UnsignedArduino** [comment]
it's SOOO hard

**Comment by D4ngerKitty** [comment]
Yes it is I had to get bother to beet it for me 
https://makecode.com/_1vvTyXi6j94p
Fixed the reset bug

**Comment by D4ngerKitty** [comment]
I have beaten it once after it was finished

**Comment by D4ngerKitty** [comment]
Oh and if you name is progamer you you will get pro mode in the final boss fight

**Comment by D4ngerKitty** [comment]
fixed some more bugs
https://makecode.com/_KJhMbX2VF3jw

**Comment by D4ngerKitty** [comment]
So when are going to submit this for the game jam

**Comment by UnsignedArduino** [comment]
you can submit it

**Comment by UnsignedArduino** [comment]
whenever you want

**Comment by D4ngerKitty** [comment]
Right now

**Comment by UnsignedArduino** [comment]
sure

**Comment by D4ngerKitty** [comment]
do you want to at any thing to it

**Comment by D4ngerKitty** [comment]
before I submit it

**Comment by UnsignedArduino** [comment]
no

**Comment by UnsignedArduino** [comment]
the latest one you sent is good

**Comment by D4ngerKitty** [comment]
Okay

**Comment by D4ngerKitty** [comment]
Last update added pro only if your name is progamer
https://makecode.com/_HwWCb79YYFA7

**Comment by UnsignedArduino** [comment]
ok

**Comment by UnsignedArduino** [comment]
i'll post it to the forum, you submit?

**Comment by D4ngerKitty** [comment]
It is 20% harder

**Comment by UnsignedArduino** [comment]
oof

**Comment by UnsignedArduino** [comment]
i'll post it on the forums

**Comment by UnsignedArduino** [comment]
i'm gonna reshare the last link you did for better thumbnail lol

**Comment by D4ngerKitty** [comment]
Okay that is fine

**Comment by D4ngerKitty** [comment]
I just summited our game to the game jam

**Comment by UnsignedArduino** [comment]
just submitted post on forum

**Comment by D4ngerKitty** [comment]
I am sort of sad that we are do it was so much fun coding with you!

**Comment by D4ngerKitty** [comment]
Do you think I should post the pro mode thing on the forum?

**Comment by D4ngerKitty** [comment]
So I am going to make some fan art of us in the woods at a desk what do you what me to draw you as
The honey Bare Kat drew 
You normal icon as a face as a robot
or what ever else you what

**Comment by UnsignedArduino** [comment]
yea, that was fun coding
you can post about the pro mode [there](https://forum.makecode.com/t/the-phoenixs-quest/11390/3)
the badger is fine :) (took me forever to find [it](https://forum.makecode.com/t/pixel-art/3715/86) lol)

**Comment by D4ngerKitty** [comment]
Okay

**Comment by D4ngerKitty** [comment]
If you ever want to make another game together I will be open because in dragoon masters there is a really bad glitch were all the tile maps change and I am wanting for that bug to be fixed

**Comment by D4ngerKitty** [comment]
Okay made the art
https://makecode.com/_8vi8wVMYwC2g

**Comment by UnsignedArduino** [comment]
@LucasMayhew would you like to submit the Phoenix's Quest to [Kiki's showcase](https://forum.makecode.com/t/submit-your-game-for-the-kikis-corner-showcase/20157?u=unsignedarduino)?
Unfortunately since it is block only, I don't think we can submit the DLC as well, but I think we can still mention it.

**Comment by D4ngerKitty** [comment]
Sure just make sure to list the extensions.

**Comment by UnsignedArduino** [comment]
I see that you are replying right now lol, are you submitting the Phoenix's Quest?

**Comment by D4ngerKitty** [comment]
I’m adding on to your post of PQ just saying my inspiration and that I’m
okay having it on the blog. Hopefully it gets approved before the PQ post
does

**Comment by UnsignedArduino** [comment]
? I didn't submit any post about TPQ yet. I was going to draft it here with your input.

**Comment by UnsignedArduino** [comment]
But if you are doing it right now, that's ok. Just wanted to make sure we don't accidentally do two of them.

**Comment by D4ngerKitty** [comment]
Oh okay. Can’t wait to see the draft then

**Comment by D4ngerKitty** [comment]
Gotcha.

**Comment by UnsignedArduino** [comment]
Handles: Lucas_M and UnsignedArduino
Time spent: ~50 hours
Inspiration: 
Difficulty: 8/10
Game: The Phoenix's Quest ([original forum post](https://forum.makecode.com/t/the-phoenixs-quest/11390?u=unsignedarduino), [original link](https://arcade.makecode.com/08184-31648-39354-45691), [The Cloudy Climb DLC forum post](https://forum.makecode.com/t/the-phoenixs-quest-the-cloudy-climb-dlc-out-now/12915?u=unsignedarduino), [The Cloudy Climb DLC link](https://arcade.makecode.com/31393-03412-94227-19662)) An extensive RPG submitted for the MakeCode Arcade 2021 Climate Crisis game jam! 
Extensions used:
- UnsignedArduino/Stats
- jwunderl/arcade-sprite-util
- riknoll/arcade-shader
- UnsignedArduino/ColorBlock
- [x] I consent to my game being showcased and talked about in Kiki’s Corner.
- [x] I’m okay with being asked interview questions.

Please suggest changes lol. The difficulty is probably lower cause I'm not a pro gamer, I think you probably spent more hours than 50 in total, the description is very lame, and what was your inspiration.

**Comment by D4ngerKitty** [comment]
Difficulty would be more like a 7 or a 6

**Comment by D4ngerKitty** [comment]
I spent about 20 - 30 hours on it my self

**Comment by D4ngerKitty** [comment]
you could also add this 
I and @LucasMayhew consent to my game being showcased and talked about in Kiki’s Corner.
 I’m and @LucasMayhew are okay with being asked interview questions.

**Comment by UnsignedArduino** [comment]
Do you want Lucas_M or LucasMayhew for handle

**Comment by D4ngerKitty** [comment]
Lucas_M

**Comment by D4ngerKitty** [comment]
![download (2)](https://github.com/LucasMayhew/Gameideas/assets/59377840/2ac39641-a977-4a9c-bb46-6543241cfc3b)
also this album made by one of my fav artist inspired the Phoenix design

**Comment by D4ngerKitty** [comment]
![download (3)](https://github.com/LucasMayhew/Gameideas/assets/59377840/1e8a6189-1a8d-44de-95fc-6b32e07533f0)
heres a better image

**Comment by D4ngerKitty** [comment]
what else could we add?

**Comment by UnsignedArduino** [comment]
Do you have a specific name for the artist/photo?

**Comment by UnsignedArduino** [comment]
This is what I have so far:

Handles: Lucas_M and UnsignedArduino
Time spent: ~50 hours
Inspiration:
Difficulty: 7/10
Game: The Phoenix's Quest ([original forum post](https://forum.makecode.com/t/the-phoenixs-quest/11390?u=unsignedarduino), [original link](https://arcade.makecode.com/08184-31648-39354-45691), [The Cloudy Climb DLC forum post](https://forum.makecode.com/t/the-phoenixs-quest-the-cloudy-climb-dlc-out-now/12915?u=unsignedarduino), [The Cloudy Climb DLC link](https://arcade.makecode.com/31393-03412-94227-19662)) An extensive RPG submitted for the MakeCode Arcade 2021 Climate Crisis game jam! Featuring a 3-slot save system, level selector, 12-level storyline, an epic boss battle, and a DLC, this game emphasizes the global climate crisis happening, and how you can help! ~~(well, maybe not fighting floating trash.)~~

Extensions used:
- UnsignedArduino/Stats
- jwunderl/arcade-sprite-util
- riknoll/arcade-shader
- UnsignedArduino/ColorBlock

- [x] @Lucas_M and I consent to my game being showcased and talked about in Kiki’s Corner.
- [x] @Lucas_M and I are okay with being asked interview questions.

**Comment by D4ngerKitty** [comment]
I guess the Inspiration could be 
Inspiration: the Phoenix design was inspired by one of Lucas_Ms favorite edm artist at the times album cover.

**Comment by D4ngerKitty** [comment]
The artist in question is MDK he's the biggest artist I listen to...

**Comment by UnsignedArduino** [comment]
I'll submit this then:

Handles: Lucas_M and UnsignedArduino
Time spent: ~50 hours
Inspiration: The Phoenix design was inspired by Lucas_M's favorite EDM artist MDK, specifically the Rise album cover.
Difficulty: 7/10
Game: The Phoenix's Quest ([original forum post](https://forum.makecode.com/t/the-phoenixs-quest/11390?u=unsignedarduino), [original link](https://arcade.makecode.com/08184-31648-39354-45691), [The Cloudy Climb DLC forum post](https://forum.makecode.com/t/the-phoenixs-quest-the-cloudy-climb-dlc-out-now/12915?u=unsignedarduino), [The Cloudy Climb DLC link](https://arcade.makecode.com/31393-03412-94227-19662)) An extensive RPG submitted for the MakeCode Arcade 2021 Climate Crisis game jam! Featuring a 3-slot save system, level selector, 12-level storyline, an epic boss battle, and a DLC, this game emphasizes the global climate crisis happening, and how you can help! ~~(well, maybe not fighting floating trash.)~~

Extensions used:
- UnsignedArduino/Stats
- jwunderl/arcade-sprite-util
- riknoll/arcade-shader
- UnsignedArduino/ColorBlock

- [x] @Lucas_M and I consent to my game being showcased and talked about in Kiki’s Corner.
- [x] @Lucas_M and I are okay with being asked interview questions.

**Comment by D4ngerKitty** [comment]
the album name is rise

**Comment by UnsignedArduino** [comment]
edited

**Comment by UnsignedArduino** [comment]
anything else?

**Comment by D4ngerKitty** [comment]
also I would like it if you didn't mention MDK, I don't like his newer music and most rise is PG 13 and I don't want to post stuff like that on the forum

**Comment by UnsignedArduino** [comment]
"The Phoenix design was inspired by an album cover from one of Lucas_M's favorite artists."?

**Comment by D4ngerKitty** [comment]
yea

**Comment by D4ngerKitty** [comment]
lets get to posting this I might post RAD as well

**Comment by UnsignedArduino** [comment]
submitting post

**Comment by UnsignedArduino** [comment]
submitted

**Comment by UnsignedArduino** [comment]
> lets get to posting this I might post RAD as well

💯

**Comment by D4ngerKitty** [comment]
okay lets goo
